language: r
cache: packages
r_check_args: --as-cran

matrix:
  include:
    - os: linux
    - os: osx
      r_check_args: --no-manual
      r_packages:
        - covr
      after_success: - Rscript -e 'covr::codecov(quiet=FALSE)'
